language: r

warnings_are_errors: true

sudo: required

cache: packages

r:
 - oldrel
 - release
 - devel

apt_packages:
  - libv8-dev
  - xclip

env:
 global:
   - CRAN: http://cran.rstudio.com

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    - bob@rud.is
  irc:
    channels:
      - "104.236.112.222#builds"
    nick: travisci
